# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('author', models.CharField(max_length=16, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Body')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Alias')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.CharField(max_length=140, verbose_name='Comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogsPost',
        ),
        migrations.AddField(
            model_name='blog',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Tags'),
        ),
    ]
